# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1camMWN0T5Qv7qGxZtavttLam5ZUa8O7c
"""

import random
import pandas as pd
import numpy as np
from datetime import datetime

SUITS = ['Acorn', 'Leaf', 'Heart', 'Bell']
RANKS = ['A', '10', 'K', 'O', 'U', '9', '8', '7']
POINT_VALUES = {'A':11, '10':10, 'K':4, 'O':3, 'U':2}

# Pre-generate deck once
FULL_DECK = [f"{r}_{s}" for s in SUITS for r in RANKS]

def trump_rank(card):
    """O_Acorn=0...O_Bell=3, U_Acorn=4...U_Bell=7, Hearts A=8...7=15, else 100."""
    rank, suit = card.split('_')
    lords = {'O_Acorn':0, 'O_Leaf':1, 'O_Heart':2, 'O_Bell':3,
             'U_Acorn':4, 'U_Leaf':5, 'U_Heart':6, 'U_Bell':7}
    if card in lords:
        return lords[card]
    if suit == 'Heart':
        heart_ranks = {'A':8, '10':9, 'K':10, 'O':11, 'U':12, '9':13, '8':14, '7':15}
        return heart_ranks[rank]
    return 100

def card_value(card):
    return POINT_VALUES.get(card.split('_')[0], 0)

def random_legal_card(hand, lead_suit):
    """Follow suit > trump > any. Returns card or None."""
    if not hand:
        return None

    same_suit = [c for c in hand if c.split('_')[1] == lead_suit]
    if same_suit:
        return random.choice(same_suit)

    trumps = [c for c in hand if trump_rank(c) < 100]
    if trumps:
        return random.choice(trumps)

    return random.choice(hand)

def find_partner(hand):
    """Declarer calls Ace they don't have."""
    aces = ['A_Acorn', 'A_Leaf', 'A_Heart', 'A_Bell']
    my_aces = {c for c in hand if c.split('_')[0] == 'A'}
    avail = [a for a in aces if a not in my_aces]
    return random.choice(avail) if avail else 'A_Acorn'

def simulate_rufer_random():
    """One Rufer game: random legal play."""
    deck = FULL_DECK[:]
    random.shuffle(deck)
    hands = [deck[i*8:(i+1)*8] for i in range(4)]

    declarer = 0
    partner_ace = find_partner(hands[declarer])

    points = [0, 0, 0, 0]
    leader = 0
    lead_suit = None

    for trick_num in range(8):
        trick = []
        for p in range(4):
            player = (leader + p) % 4
            card = random_legal_card(hands[player], lead_suit)
            if card:
                hands[player].remove(card)
                trick.append((player, card))

        if not trick:
            break

        # Winner: lowest trump_rank
        winner = min(trick, key=lambda x: trump_rank(x[1]))[0]
        trick_points = sum(card_value(c[1]) for c in trick)
        points[winner] += trick_points

        leader = winner
        lead_suit = trick[0][1].split('_')[1]  # Next lead suit

    # Find partner (who holds called Ace)
    partner = 1
    for i in range(1, 4):
        if any(partner_ace == c for c in FULL_DECK if c not in hands[i]):
            # Partner is whoever has the called Ace
            pass
    # Simplified: assume partner is player 1 (can improve detection)
    declarer_points = points[declarer] + points[1]

    win = declarer_points >= 61
    schneider = declarer_points >= 91
    schwarz = declarer_points == 120

    return {
        'declarer_pts': declarer_points,
        'opponent_pts': 120 - declarer_points,
        'win': win,
        'schneider': schneider,
        'schwarz': schwarz
    }

# Run 100k games efficiently
num_games = 100000
batch_size = 10000
all_results = []

print(f"Starting {num_games} Rufer simulations...")
start_time = datetime.now()

for batch in range(num_games // batch_size):
    batch_results = [simulate_rufer_random() for _ in range(batch_size)]
    all_results.extend(batch_results)
    elapsed = (datetime.now() - start_time).total_seconds()
    rate = (batch + 1) * batch_size / elapsed
    print(f"[{(batch+1)*batch_size:,}/{num_games:,}] {rate:.0f} games/sec | {elapsed:.1f}s elapsed")

df = pd.DataFrame(all_results)
df.to_csv('random_rufer_100k.csv', index=False)

# Stats
print("" + "="*50)
print("RUFER RANDOM 100K GAME STATISTICS")
print("="*50)
print(f"Win Rate (Declarer):")
print(df['win'].value_counts(normalize=True))
print(f"Mean Declarer Points: {df['declarer_pts'].mean():.2f}")
print(f"Median Declarer Points: {df['declarer_pts'].median():.0f}")
print(f"Std Dev: {df['declarer_pts'].std():.2f}")
print(f"Schneider (91+): {df['schneider'].mean():.2%}")
print(f"Schwarz (120): {df['schwarz'].mean():.2%}")
print(f"Total time: {(datetime.now() - start_time).total_seconds():.1f}s")
print(f"CSV saved: random_rufer_100k.csv ({len(df)} rows)")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Load data
df = pd.read_csv('random_rufer_100k.csv')
print("Data loaded:", df.shape)
print(df.head())

# Create comprehensive visualizations
fig = plt.figure(figsize=(20, 16))

## 1. HISTOGRAM - All Data Points
ax1 = plt.subplot(3, 3, (1, 2))
bins = np.arange(0, 121, 2)
n, bins, patches = plt.hist(df['declarer_pts'], bins=bins, alpha=0.7, color='skyblue', edgecolor='black')
plt.axvline(61, color='red', linestyle='--', linewidth=2, label='Win threshold (61)')
plt.axvline(df['declarer_pts'].mean(), color='orange', linestyle='-', linewidth=2, label=f'Mean: {df["declarer_pts"].mean():.1f}')
plt.xlabel('Declarer Points')
plt.ylabel('Frequency')
plt.title('Distribution of Declarer Points (100k Games)', fontsize=14, fontweight='bold')
plt.legend()
plt.grid(True, alpha=0.3)

## 2. HEATMAP - 5-Point Increments
ax2 = plt.subplot(3, 3, 3)
df['pts_bin'] = (df['declarer_pts'] // 5 * 5).astype(int)
heatmap_data = df['pts_bin'].value_counts().sort_index().reindex(range(0, 121, 5), fill_value=0)
bins_5pt = np.arange(0, 121, 5)
plt.bar(range(len(heatmap_data)), heatmap_data.values, width=0.8, color='gold', alpha=0.8)
plt.xticks(range(0, len(heatmap_data), 4), bins_5pt[::4], rotation=45)
plt.xlabel('Declarer Points (5-pt bins)')
plt.ylabel('Frequency')
plt.title('Frequency by 5-Point Increments')
plt.grid(True, alpha=0.3)

## 3. OUTLIER BOXPLOT
ax3 = plt.subplot(3, 3, 4)
bp = plt.boxplot([df['declarer_pts'], df[df['win']]['declarer_pts'], df[~df['win']]['declarer_pts']],
                 labels=['All', 'Wins', 'Losses'], patch_artist=True)
plt.ylabel('Declarer Points')
plt.title('Outliers: Boxplot Comparison')
colors = ['lightblue', 'lightgreen', 'lightcoral']
for patch, color in zip(bp['boxes'], colors):
    patch.set_facecolor(color)

## 4. CUMULATIVE DISTRIBUTION
ax4 = plt.subplot(3, 3, 5)
sorted_pts = np.sort(df['declarer_pts'])
yvals = np.arange(len(sorted_pts))/float(len(sorted_pts))
plt.plot(sorted_pts, yvals, 'b-', linewidth=2)
plt.axvline(61, color='red', linestyle='--', label=f'61 pts ({df["win"].mean():.1%})')
plt.xlabel('Declarer Points')
plt.ylabel('Cumulative Probability')
plt.title('Cumulative Distribution Function')
plt.legend()
plt.grid(True, alpha=0.3)

## 5. VIOLIN PLOT
ax5 = plt.subplot(3, 3, 6)
vp = plt.violinplot([df[df['win']]['declarer_pts'], df[~df['win']]['declarer_pts']],
                   positions=[1, 2], widths=0.6, showmeans=True)
vp['cbars'].set_color('red')
vp['cmins'].set_color('red')
vp['cmaxes'].set_color('red')
plt.xticks([1, 2], ['Wins', 'Losses'])
plt.ylabel('Declarer Points')
plt.title('Win vs Loss Density')

## 6. OUTCOME PIE
ax6 = plt.subplot(3, 3, 7)
categories = ['Loss (<61)', 'Win (61-90)', 'Schneider (91+)', 'Schwarz (120)']
counts = [
    len(df[df['declarer_pts'] < 61]),
    len(df[(df['declarer_pts'] >= 61) & (df['declarer_pts'] < 91)]),
    len(df[df['declarer_pts'] >= 91]),
    len(df[df['declarer_pts'] == 120])
]
plt.pie(counts, labels=categories, autopct='%1.1f%%', startangle=90)
plt.title('Outcome Breakdown')

## 7. DENSITY OVERLAY
ax7 = plt.subplot(3, 3, 8)
sns.kdeplot(data=df, x='declarer_pts', hue='win', fill=True, alpha=0.5, palette=['red','green'])
plt.xlabel('Declarer Points')
plt.ylabel('Density')
plt.title('Win/Loss Density Overlay')
plt.legend(labels=['Loss', 'Win'])

## 8. TOP 5-POINT BINS TABLE
ax8 = plt.subplot(3, 3, 9)
bin_freq = (df['declarer_pts'] // 5 * 5).value_counts().sort_values(ascending=False).head(10)
table_data = [[f"{bin_freq.index[i]} pts", f"{bin_freq.values[i]:,}", f"{bin_freq.values[i]/len(df)*100:.1f}%"]
              for i in range(len(bin_freq))]
table = ax8.table(cellText=table_data,
                  colLabels=['Points Bin', 'Frequency', '% of Games'],
                  cellLoc='center', loc='center')
table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 2)
ax8.axis('off')
ax8.set_title('Top 10 Most Frequent 5-pt Bins')

plt.tight_layout()
plt.savefig('schafkopf_analysis_full.png', dpi=300, bbox_inches='tight')
plt.show()

# Clean single-line prints
print("================================================================")
print("SCHAFKOPF RUFER 100K ANALYSIS SUMMARY")
print("================================================================")
print(f"Total Games: {len(df):,}")
print(f"Win Rate: {df['win'].mean():.3%}")
print(f"Mean Points: {df['declarer_pts'].mean():.1f} ± {df['declarer_pts'].std():.1f}")
print(f"Median: {df['declarer_pts'].median():.0f}")
print(f"Schneider Rate (91+): {df['schneider'].mean():.2%}")
print(f"Schwarz Rate (120): {df['schwarz'].mean():.2%}")

mean_pts = df['declarer_pts'].mean()
std_pts = df['declarer_pts'].std()
outliers_high = df[df['declarer_pts'] > mean_pts + 3*std_pts]
outliers_low = df[df['declarer_pts'] < mean_pts - 3*std_pts]

print(f"Outliers (>3σ from mean {mean_pts:.1f}):")
print(f"  Extreme High (>{mean_pts+3*std_pts:.0f}): {len(outliers_high)} ({len(outliers_high)/len(df)*100:.2f}%)")
print(f"  Extreme Low (<{mean_pts-3*std_pts:.0f}):  {len(outliers_low)} ({len(outliers_low)/len(df)*100:.2f}%)")

print("Top 5-Point Bins (Most Frequent):")
bin_freq = (df['declarer_pts'] // 5 * 5).value_counts().sort_values(ascending=False).head(10)
for pts, freq in bin_freq.items():
    print(f"  {pts:3d} pts: {freq:6,} games ({freq/len(df)*100:5.1f}%)")

print("Files saved: schafkopf_analysis_full.png")

import pandas as pd
import numpy as np
import random
from itertools import combinations
from collections import Counter

SUITS = ['Acorn', 'Leaf', 'Heart', 'Bell']
RANKS = ['A', '10', 'K', 'O', 'U', '9', '8', '7']
POINT_VALUES = {'A':11, '10':10, 'K':4, 'O':3, 'U':2, '9':0, '8':0, '7':0}
FULL_DECK = [f"{r}_{s}" for s in SUITS for r in RANKS]

# Global ordered trump list: 0 = strongest, 15 = weakest
TRUMP_ORDER = [
    'O_Acorn','O_Leaf','O_Heart','O_Bell',
    'U_Acorn','U_Leaf','U_Heart','U_Bell',
    'A_Heart','10_Heart','K_Heart','O_Heart','U_Heart','9_Heart','8_Heart','7_Heart'
]  # suits ignored, rank index is what matters

TRUMP_INDEX = {c:i for i,c in enumerate(TRUMP_ORDER)}

def trump_rank(card):
    """Return 0–15 for trumps, 100 for non‑trumps (Rufer)."""
    if card in TRUMP_INDEX:
        return TRUMP_INDEX[card]
    rank, suit = card.split('_')
    if suit == 'Heart':  # non‑lord hearts
        # map remaining hearts into back of trump range if not already in TRUMP_INDEX
        if card not in TRUMP_INDEX:
            # Fallback: treat as weak trump
            return 99
    return 100

def card_value(card):
    return POINT_VALUES.get(card.split('_')[0], 0)

def featurize_hand(hand):
    trump_cards = [c for c in hand if trump_rank(c) < 100]
    suit_counts = Counter([c.split('_')[1] for c in hand])
    max_suit_count = max(suit_counts.values()) if suit_counts else 0
    non_trump_points = sum(card_value(c) for c in hand if trump_rank(c) >= 100)

    # vector of which trump ranks (0–15) are present
    trump_ranks_present = sorted(trump_rank(c) for c in trump_cards)
    # for signature we only store summary, detailed list can be re‑derived if needed
    highest_trump = min(trump_ranks_present) if trump_ranks_present else 999
    lowest_trump = max(trump_ranks_present) if trump_ranks_present else 999

    return {
        'trump_count'        : len(trump_cards),
        'highest_trump_rank' : highest_trump,  # 0 = strongest
        'lowest_trump_rank'  : lowest_trump,   # 15 = weakest
        'max_suit_count'     : max_suit_count,
        'total_points'       : sum(card_value(c) for c in hand),
        'non_trump_points'   : non_trump_points
    }

def hand_signature(hand):
    f = featurize_hand(hand)
    # signature ignores colors: only strength pattern matters
    return (
        f['trump_count'],
        f['highest_trump_rank'],
        f['lowest_trump_rank'],
        f['max_suit_count'],
        f['total_points']
    )

def random_legal_card(hand, lead_suit):
    if not hand:
        return None
    same_suit = [c for c in hand if c.split('_')[1] == lead_suit]
    if same_suit:
        return random.choice(same_suit)
    trumps = [c for c in hand if trump_rank(c) < 100]
    if trumps:
        return random.choice(trumps)
    return random.choice(hand)

def find_partner(hand):
    aces = ['A_Acorn', 'A_Leaf', 'A_Heart', 'A_Bell']
    my_aces = {c for c in hand if c.split('_')[0] == 'A'}
    avail = [a for a in aces if a not in my_aces]
    return random.choice(avail) if avail else 'A_Acorn'

def simulate_rufer_with_hand(declarer_hand, num_sims=50):
    wins = 0
    total_pts = []

    for _ in range(num_sims):
        deck = [c for c in FULL_DECK if c not in declarer_hand]
        random.shuffle(deck)
        hands = [declarer_hand[:], deck[0:8], deck[8:16], deck[16:24]]

        partner_ace = find_partner(declarer_hand)
        points = [0, 0, 0, 0]
        leader = 0
        lead_suit = None

        for _ in range(8):
            trick = []
            for p in range(4):
                card = random_legal_card(hands[p], lead_suit)
                if card:
                    hands[p].remove(card)
                    trick.append((p, card))
            if not trick:
                break

            winner = min(trick, key=lambda x: trump_rank(x[1]))[0]
            points[winner] += sum(card_value(c[1]) for c in trick)
            leader = winner
            lead_suit = trick[0][1].split('_')[1]

        # simplified: assume partner is player 1
        declarer_pts = points[0] + points[1]
        wins += 1 if declarer_pts >= 61 else 0
        total_pts.append(declarer_pts)

    return wins / num_sims, float(np.mean(total_pts))

# ---------------- sampling over hand space ----------------

all_hands = list(combinations(FULL_DECK, 8))
hand_stats = {}

print(f"Total possible hands: {len(all_hands):,}")
print("Sampling hands by signature (grouping by rank/suit patterns)...")

step = max(1, len(all_hands)//1000)  # sample ~1000 hands

for i, hand in enumerate(all_hands[::step]):
    sig = hand_signature(list(hand))
    if sig not in hand_stats:
        win_rate, avg_pts = simulate_rufer_with_hand(list(hand), num_sims=100)
        hand_stats[sig] = {'win_rate': win_rate, 'avg_pts': avg_pts, 'count': 1}
    else:
        hand_stats[sig]['count'] += 1

    if (i+1) % 100 == 0:
        print(f"Processed {i+1} hands, {len(hand_stats)} unique signatures")

df_hands = pd.DataFrame([
    {
        'trump_count'       : k[0],
        'highest_trump_rank': k[1],
        'lowest_trump_rank' : k[2],
        'max_suit'          : k[3],
        'total_points'      : k[4],
        'win_rate'          : v['win_rate'],
        'avg_pts'           : v['avg_pts']
    }
    for k, v in hand_stats.items()
])

df_hands = df_hands.sort_values('win_rate', ascending=False)
df_hands.to_csv('hand_strength_analysis.csv', index=False)

print("="*70)
print("TOP 20 STRONGEST STARTING HANDS (by win rate)")
print("="*70)
print(df_hands.head(20).to_string(index=False))

print("="*70)
print("BOTTOM 20 WEAKEST STARTING HANDS")
print("="*70)
print(df_hands.tail(20).to_string(index=False))

print(f"CSV saved: hand_strength_analysis.csv ({len(df_hands)} unique hand signatures)")
print(f"Win Rate Range: {df_hands['win_rate'].min():.1%} to {df_hands['win_rate'].max():.1%}")

import pandas as pd
import numpy as np
import random
from itertools import combinations
from collections import Counter

SUITS = ['Acorn', 'Leaf', 'Heart', 'Bell']
RANKS = ['A', '10', 'K', 'O', 'U', '9', '8', '7']
POINT_VALUES = {'A':11, '10':10, 'K':4, 'O':3, 'U':2, '9':0, '8':0, '7':0}
FULL_DECK = [f"{r}_{s}" for s in SUITS for r in RANKS]

# Correct ordered trump list, each card once, strongest → weakest
TRUMP_ORDER = [
    'O_Acorn','O_Leaf','O_Heart','O_Bell',
    'U_Acorn','U_Leaf','U_Heart','U_Bell',
    'A_Heart','10_Heart','K_Heart','9_Heart','8_Heart','7_Heart'
]
TRUMP_INDEX = {c: i for i, c in enumerate(TRUMP_ORDER)}

def trump_rank(card):
    """Return 0..(len(TRUMP_ORDER)-1) for trumps, 100 for non‑trumps."""
    return TRUMP_INDEX.get(card, 100)

def card_value(card):
    return POINT_VALUES.get(card.split('_')[0], 0)

def featurize_hand(hand):
    trump_cards = [c for c in hand if trump_rank(c) < 100]
    suit_counts = Counter([c.split('_')[1] for c in hand])
    max_suit_count = max(suit_counts.values()) if suit_counts else 0
    non_trump_points = sum(card_value(c) for c in hand if trump_rank(c) >= 100)

    if trump_cards:
        ranks_present = [trump_rank(c) for c in trump_cards]
        highest_trump = min(ranks_present)  # 0 = strongest Ober
        lowest_trump  = max(ranks_present)  # larger index = weaker
    else:
        # No trumps in hand: encode as -1, not 999
        highest_trump = -1
        lowest_trump  = -1

    return {
        'trump_count': len(trump_cards),
        'highest_trump_rank': highest_trump,
        'lowest_trump_rank': lowest_trump,
        'max_suit_count': max_suit_count,
        'total_points': sum(card_value(c) for c in hand),
        'non_trump_points': non_trump_points,
    }

def hand_signature(hand):
    f = featurize_hand(hand)
    return (
        f['trump_count'],
        f['highest_trump_rank'],
        f['lowest_trump_rank'],
        f['max_suit_count'],
        f['total_points'],
    )

def random_legal_card(hand, lead_suit):
    if not hand:
        return None
    same_suit = [c for c in hand if c.split('_')[1] == lead_suit]
    if same_suit:
        return random.choice(same_suit)
    trumps = [c for c in hand if trump_rank(c) < 100]
    if trumps:
        return random.choice(trumps)
    return random.choice(hand)

def find_partner(hand):
    aces = ['A_Acorn', 'A_Leaf', 'A_Heart', 'A_Bell']
    my_aces = {c for c in hand if c.split('_')[0] == 'A'}
    avail = [a for a in aces if a not in my_aces]
    return random.choice(avail) if avail else 'A_Acorn'

def simulate_rufer_with_hand(declarer_hand, num_sims=50):
    wins = 0
    total_pts = []

    for _ in range(num_sims):
        deck = [c for c in FULL_DECK if c not in declarer_hand]
        random.shuffle(deck)
        hands = [declarer_hand[:], deck[0:8], deck[8:16], deck[16:24]]

        partner_ace = find_partner(declarer_hand)
        points = [0, 0, 0, 0]
        leader = 0
        lead_suit = None

        for _ in range(8):
            trick = []
            for p in range(4):
                card = random_legal_card(hands[p], lead_suit)
                if card:
                    hands[p].remove(card)
                    trick.append((p, card))
            if not trick:
                break
            winner = min(trick, key=lambda x: trump_rank(x[1]))[0]
            points[winner] += sum(card_value(c[1]) for c in trick)
            leader = winner
            lead_suit = trick[0][1].split('_')[1]

        # simplified: partner assumed player 1
        declarer_pts = points[0] + points[1]
        wins += int(declarer_pts >= 61)
        total_pts.append(declarer_pts)

    return wins / num_sims, float(np.mean(total_pts))

# -------- sampling --------

all_hands = list(combinations(FULL_DECK, 8))
hand_stats = {}

print(f"Total possible hands: {len(all_hands):,}")
print("Sampling hands by signature (grouping by rank/suit patterns)...")

step = max(1, len(all_hands) // 1000)  # ~1000 samples

for i, hand in enumerate(all_hands[::step]):
    sig = hand_signature(list(hand))
    if sig not in hand_stats:
        win_rate, avg_pts = simulate_rufer_with_hand(list(hand), num_sims=100)
        hand_stats[sig] = {'win_rate': win_rate, 'avg_pts': avg_pts, 'count': 1}
    else:
        hand_stats[sig]['count'] += 1

    if (i + 1) % 100 == 0:
        print(f"Processed {i+1} hands, {len(hand_stats)} unique signatures")

df_hands = pd.DataFrame([
    {
        'trump_count': k[0],
        'highest_trump_rank': k[1],
        'lowest_trump_rank': k[2],
        'max_suit': k[3],
        'total_points': k[4],
        'win_rate': v['win_rate'],
        'avg_pts': v['avg_pts'],
    }
    for k, v in hand_stats.items()
])

df_hands = df_hands.sort_values('win_rate', ascending=False)
df_hands.to_csv('hand_strength_analysis_fixed.csv', index=False)

print("=" * 70)
print("TOP 20 STRONGEST STARTING HANDS (by win rate)")
print("=" * 70)
print(df_hands.head(20).to_string(index=False))

print("=" * 70)
print("BOTTOM 20 WEAKEST STARTING HANDS")
print("=" * 70)
print(df_hands.tail(20).to_string(index=False))

print(f"CSV saved: hand_strength_analysis_fixed.csv ({len(df_hands)} unique signatures)")
print(f"Win Rate Range: {df_hands['win_rate'].min():.1%} "
      f"to {df_hands['win_rate'].max():.1%}")

import pandas as pd
import numpy as np
import random
from itertools import combinations
from collections import Counter

SUITS = ['Acorn', 'Leaf', 'Heart', 'Bell']
RANKS = ['A', '10', 'K', 'O', 'U', '9', '8', '7']
POINT_VALUES = {'A':11, '10':10, 'K':4, 'O':3, 'U':2, '9':0, '8':0, '7':0}
FULL_DECK = [f"{r}_{s}" for s in SUITS for r in RANKS]

# Correct ordered trump list, each card once, strongest → weakest
TRUMP_ORDER = [
    'O_Acorn','O_Leaf','O_Heart','O_Bell',
    'U_Acorn','U_Leaf','U_Heart','U_Bell',
    'A_Heart','10_Heart','K_Heart','9_Heart','8_Heart','7_Heart'
]
TRUMP_INDEX = {c: i for i, c in enumerate(TRUMP_ORDER)}

def trump_rank(card):
    """Return 0..(len(TRUMP_ORDER)-1) for trumps, 100 for non-trumps."""
    return TRUMP_INDEX.get(card, 100)

def card_value(card):
    return POINT_VALUES.get(card.split('_')[0], 0)

def featurize_hand(hand):
    trump_cards = [c for c in hand if trump_rank(c) < 100]
    suit_counts = Counter([c.split('_')[1] for c in hand])
    max_suit_count = max(suit_counts.values()) if suit_counts else 0
    non_trump_points = sum(card_value(c) for c in hand if trump_rank(c) >= 100)

    if trump_cards:
        ranks_present = [trump_rank(c) for c in trump_cards]
        highest_trump = min(ranks_present)      # 0 = strongest Ober
        lowest_trump  = max(ranks_present)      # larger index = weaker
    else:
        # No trumps in hand: encode display value "--"
        highest_trump = "--"
        lowest_trump  = "--"

    return {
        'trump_count': len(trump_cards),
        'highest_trump_rank': highest_trump,
        'lowest_trump_rank': lowest_trump,
        'max_suit_count': max_suit_count,
        'total_points': sum(card_value(c) for c in hand),
        'non_trump_points': non_trump_points,
    }

def hand_signature(hand):
    f = featurize_hand(hand)
    return (
        f['trump_count'],
        f['highest_trump_rank'],
        f['lowest_trump_rank'],
        f['max_suit_count'],
        f['total_points'],
    )

def random_legal_card(hand, lead_suit):
    if not hand:
        return None
    same_suit = [c for c in hand if c.split('_')[1] == lead_suit]
    if same_suit:
        return random.choice(same_suit)
    trumps = [c for c in hand if trump_rank(c) < 100]
    if trumps:
        return random.choice(trumps)
    return random.choice(hand)

def find_partner(hand):
    aces = ['A_Acorn', 'A_Leaf', 'A_Heart', 'A_Bell']
    my_aces = {c for c in hand if c.split('_')[0] == 'A'}
    avail = [a for a in aces if a not in my_aces]
    return random.choice(avail) if avail else 'A_Acorn'

def simulate_rufer_with_hand(declarer_hand, num_sims=50):
    wins = 0
    total_pts = []

    for _ in range(num_sims):
        deck = [c for c in FULL_DECK if c not in declarer_hand]
        random.shuffle(deck)
        hands = [declarer_hand[:], deck[0:8], deck[8:16], deck[16:24]]

        partner_ace = find_partner(declarer_hand)
        points = [0, 0, 0, 0]
        leader = 0
        lead_suit = None

        for _ in range(8):
            trick = []
            for p in range(4):
                card = random_legal_card(hands[p], lead_suit)
                if card:
                    hands[p].remove(card)
                    trick.append((p, card))
            if not trick:
                break
            winner = min(trick, key=lambda x: trump_rank(x[1]))[0]
            points[winner] += sum(card_value(c[1]) for c in trick)
            leader = winner
            lead_suit = trick[0][1].split('_')[1]

        # simplified: partner assumed player 1
        declarer_pts = points[0] + points[1]
        wins += int(declarer_pts >= 61)
        total_pts.append(declarer_pts)

    return wins / num_sims, float(np.mean(total_pts))

# -------- sampling --------

all_hands = list(combinations(FULL_DECK, 8))
hand_stats = {}

print(f"Total possible hands: {len(all_hands):,}")
print("Sampling hands by signature (grouping by rank/suit patterns)...")

step = max(1, len(all_hands) // 100000)  # ~1000 samples

for i, hand in enumerate(all_hands[::step]):
    sig = hand_signature(list(hand))
    if sig not in hand_stats:
        win_rate, avg_pts = simulate_rufer_with_hand(list(hand), num_sims=100)
        hand_stats[sig] = {'win_rate': win_rate, 'avg_pts': avg_pts, 'count': 1}
    else:
        hand_stats[sig]['count'] += 1

    if (i + 1) % 100 == 0:
        print(f"Processed {i+1} hands, {len(hand_stats)} unique signatures")

df_hands = pd.DataFrame([
    {
        'trump_count': k[0],
        'highest_trump_rank': k[1],
        'lowest_trump_rank': k[2],
        'max_suit': k[3],
        'total_points': k[4],
        'win_rate': v['win_rate'],
        'avg_pts': v['avg_pts'],
    }
    for k, v in hand_stats.items()
])

df_hands = df_hands.sort_values('win_rate', ascending=False)
df_hands.to_csv('hand_strength_analysis_fixed.csv', index=False)

print("=" * 70)
print("TOP 20 STRONGEST STARTING HANDS (by win rate)")
print("=" * 70)
print(df_hands.head(20).to_string(index=False))

print("=" * 70)
print("BOTTOM 20 WEAKEST STARTING HANDS")
print("=" * 70)
print(df_hands.tail(20).to_string(index=False))

print(f"CSV saved: hand_strength_analysis_fixed.csv ({len(df_hands)} unique signatures)")
print(f"Win Rate Range: {df_hands['win_rate'].min():.1%} "
      f"to {df_hands['win_rate'].max():.1%}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the hand strength analysis
df = pd.read_csv('hand_strength_analysis_fixed.csv')

# Convert "--" to NaN for numeric operations (but keep for display)
df_numeric = df.copy()
df_numeric['highest_trump_rank'] = pd.to_numeric(df_numeric['highest_trump_rank'], errors='coerce')
df_numeric['lowest_trump_rank'] = pd.to_numeric(df_numeric['lowest_trump_rank'], errors='coerce')

# Create figure with subplots
fig = plt.figure(figsize=(18, 12))

# ============ PLOT 1: Trump Count vs Win Probability ============
ax1 = plt.subplot(2, 2, 1)
trump_win = df_numeric.groupby('trump_count')['win_rate'].agg(['mean', 'std', 'count']).reset_index()
ax1.errorbar(trump_win['trump_count'], trump_win['mean'], yerr=trump_win['std'],
             fmt='o-', capsize=5, capthick=2, markersize=8, linewidth=2, color='steelblue')
ax1.set_xlabel('Number of Trumps', fontsize=12, fontweight='bold')
ax1.set_ylabel('Average Win Probability', fontsize=12, fontweight='bold')
ax1.set_title('Trump Count vs Win Probability', fontsize=14, fontweight='bold')
ax1.grid(True, alpha=0.3)
ax1.set_xticks(range(0, 9))

# ============ PLOT 2: Trump Strength (Highest + Lowest) vs Win Prob ============
ax2 = plt.subplot(2, 2, 2)
# Create synthetic "trump strength" score: avg of highest and lowest rank
df_numeric['trump_strength'] = (df_numeric['highest_trump_rank'] + df_numeric['lowest_trump_rank']) / 2
# Filter out NaN (no-trump hands)
df_with_trumps = df_numeric[df_numeric['trump_strength'].notna()]
scatter = ax2.scatter(df_with_trumps['trump_strength'], df_with_trumps['win_rate'],
                      c=df_with_trumps['trump_count'], cmap='viridis', s=100, alpha=0.6, edgecolors='black')
ax2.set_xlabel('Trump Strength Score (Avg of Highest + Lowest Rank)', fontsize=12, fontweight='bold')
ax2.set_ylabel('Win Probability', fontsize=12, fontweight='bold')
ax2.set_title('Trump Strength vs Win Probability (colored by trump count)', fontsize=14, fontweight='bold')
ax2.grid(True, alpha=0.3)
cbar = plt.colorbar(scatter, ax=ax2)
cbar.set_label('Trump Count', fontsize=10)

# ============ PLOT 3: Detailed scatter - Trump Count + Strength vs Win Rate ============
ax3 = plt.subplot(2, 2, 3)
for tc in sorted(df_numeric['trump_count'].unique()):
    subset = df_numeric[df_numeric['trump_count'] == tc]
    ax3.scatter(subset['highest_trump_rank'], subset['win_rate'],
               label=f'{int(tc)} trumps', s=80, alpha=0.6, edgecolors='black')
ax3.set_xlabel('Highest Trump Rank (0=strongest)', fontsize=12, fontweight='bold')
ax3.set_ylabel('Win Probability', fontsize=12, fontweight='bold')
ax3.set_title('Highest Trump Rank vs Win Rate (by trump count)', fontsize=14, fontweight='bold')
ax3.legend(loc='best', fontsize=9)
ax3.grid(True, alpha=0.3)

# ============ PLOT 4: Distribution of Win Rates ============
ax4 = plt.subplot(2, 2, 4)
ax4.hist(df_numeric['win_rate'], bins=30, color='coral', edgecolor='black', alpha=0.7)
ax4.axvline(df_numeric['win_rate'].mean(), color='red', linestyle='--', linewidth=2, label=f'Mean: {df_numeric["win_rate"].mean():.3f}')
ax4.axvline(df_numeric['win_rate'].median(), color='green', linestyle='--', linewidth=2, label=f'Median: {df_numeric["win_rate"].median():.3f}')
ax4.set_xlabel('Win Probability', fontsize=12, fontweight='bold')
ax4.set_ylabel('Frequency', fontsize=12, fontweight='bold')
ax4.set_title('Distribution of Win Rates Across All Hand Patterns', fontsize=14, fontweight='bold')
ax4.legend()
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('hand_strength_visualizations.png', dpi=300, bbox_inches='tight')
plt.show()

# ============ INVESTIGATE LOW TRUMP, HIGH WIN HANDS ============
print("
" + "="*80)
print("INVESTIGATION: LOW TRUMP (<= 3) BUT HIGH WIN PROBABILITY (>= 0.95)")
print("="*80)

low_trump_high_win = df_numeric[(df_numeric['trump_count'] <= 3) & (df_numeric['win_rate'] >= 0.95)]
low_trump_high_win = low_trump_high_win.sort_values('win_rate', ascending=False)

print(f"Found {len(low_trump_high_win)} hands with <= 3 trumps and >= 95% win rate
")
print(low_trump_high_win[['trump_count', 'highest_trump_rank', 'lowest_trump_rank',
                          'total_points', 'max_suit', 'win_rate', 'avg_pts']].head(30).to_string(index=False))

# Analyze what makes these hands strong
if len(low_trump_high_win) > 0:
    print(f"
--- Characteristics of Low-Trump High-Win Hands ---")
    print(f"Average total_points: {low_trump_high_win['total_points'].mean():.1f}")
    print(f"Average max_suit: {low_trump_high_win['max_suit'].mean():.1f}")
    print(f"Average trump_count: {low_trump_high_win['trump_count'].mean():.1f}")
    print(f"Total points range: {low_trump_high_win['total_points'].min():.0f} - {low_trump_high_win['total_points'].max():.0f}")

# Also check hands with 0 trumps but still decent win rate
print("
" + "="*80)
print("INVESTIGATION: ZERO TRUMPS BUT POSITIVE WIN RATE")
print("="*80)

zero_trump = df_numeric[df_numeric['trump_count'] == 0]
if len(zero_trump) > 0:
    zero_trump = zero_trump.sort_values('win_rate', ascending=False)
    print(f"Found {len(zero_trump)} hands with 0 trumps
")
    print(zero_trump[['trump_count', 'total_points', 'max_suit', 'win_rate', 'avg_pts']].head(20).to_string(index=False))
    print(f"
Average win rate with 0 trumps: {zero_trump['win_rate'].mean():.3f}")
    print(f"Max win rate with 0 trumps: {zero_trump['win_rate'].max():.3f}")
    print(f"Average total_points (0 trump): {zero_trump['total_points'].mean():.1f}")

print("
Visualizations saved to: hand_strength_visualizations.png")